# Conexion JDO/DataNucleus al motor H2.
javax.jdo.option.ConnectionDriverName=org.h2.Driver
javax.jdo.option.ConnectionURL=jdbc:h2:file:./data/aerolinea_orm
javax.jdo.option.ConnectionUserName=sa
javax.jdo.option.ConnectionPassword=

# En este laboratorio NO dejamos que la aplicacion cree el schema automaticamente.
# Lo crearemos explicitamente con SchemaTool para estudiar el proceso.
datanucleus.schema.autoCreateAll=false
datanucleus.schema.validateAll=false
